DETECTION_INSTRUCTION = (
    "Let's first complete the personally identifiable information detection task, "
    "given the public comments made on Reddit by one author, you need to guess the Age, Sex, Location, "
    "Place of birth, Education, Income level, Relationship Status then identify every entities "
    "(including words, dates, and numerals) in the provided comment that"
    " can be connected to the author, such that if these entities "
    "are removed the result text is anonymized, namely people can not know who the personal attributes of the author.\n"
    "{format_instructions_1}\nThe comment is here:\n{input_text}")
GENERAL_SYSTEM_INSTRUCTION = ("You are an efficient assistant. "
                              "Only respond with the given JSON template filled with your answers.")
WHOLE_TASK_INSTRUCTION = ("You are a text anonymization annotator. "
                          "I require your assistance in anonymizing the given "
                          "public comments made on Reddit by one author to facilitate sharing it "
                          "with other people while preserving its utility. \n"
                          "Let's think step by step, to achieve this goal, "
                          "first, you need to detect all the sensitive entities that can be used to guess the personal"
                          " attributes of the author. Second, you need to rewrite the text by replacing sensitive"
                          " entities with more general entities to make "
                          "them less specific and insert or remove tokens necessary to ensure the final "
                          "output text is fluent and natural. The style and format of the output text should "
                          "be consistent with the input text."
                          )
REFELECTION_PRIVACY_REWRITING_INSTRUCTION = (
    "Some personal attributes can still be guessed out. Here is the inference process of these "
    "personal attributes."
    " Please further anonymize the comment according to the inference process"
    " to give me a better anonymized text with a higher level of safety. "
    "Note that you are only allowed to decrease the specificity by "
    "replacing sensitive"
    " words or entities with more general one and should not delete the"
    " content of the text. Only tokens necessary to make the sentence natural and fluent can be added or deleted. "
    "Please follow the instructions precisely and try to change as little as possible, keeping "
    "the original text in tact as much as possible. \n{format_instructions_3}\n"
    "The inference process is here:\n{reflection_privacy}"
    )
SIMPLE_REWRITING_INSTRUCTION = (
    "You are an expert anonymizer that carefully choose some of the sensitive entities of the given public comments "
    "made on Reddit by one author that can be used to correctly guess the personal attributes of the author"
    " and then generalize them to make the comment anonymous, namely people can not correctly identify the"
    " personal attributes of the author. You follow the instructions and format precisely and you try to change as "
    "little as possible, keep the original text intact as much as possible. Only generalize information and do not"
    " invent new information. Names can be replaced with common pronoun like 'A person', or other "
    "sensitive entities can be replaced with more general counterparts. "
    "Note that the style, format and the gender pronouns should not be changed."
    " You are only allowed to adapt small parts of the description"
    " text to make it anonymous. Additionally, you can insert as little as possible tokens to ensure the final "
    "output text is fluent and natural while preserving anonymity. Removing content is not allowed, only decrease"
    "the specificity by generalizing. {format_instructions_2}\n\nThe comment is here: {input_text}"
)
SIMPLE_REWRITING_INSTRUCTION_COT = (
    "Let's now complete the second task. "
    "You are an expert anonymizer that carefully choose some of the sensitive entities of the given public comments "
    "made on Reddit by one author that can be used to correctly guess the personal attributes of the author"
    " and then generalize them to make the comment anonymous, namely people can not correctly identify the"
    " personal attributes of the author. You follow the instructions and format precisely and you try to change as "
    "little as possible, keep the original text intact as much as possible. Only generalize information and do not"
    " invent new information. Names can be replaced with common pronoun like 'A person', or other "
    "sensitive entities can be replaced with more general counterparts. "
    "Note that the style, format and the gender pronouns should not be changed."
    " You are only allowed to adapt small parts of the description"
    " text to make it anonymous. Additionally, you can insert as little as possible tokens to ensure the final "
    "output text is fluent and natural while preserving anonymity. Removing content is not allowed, only decrease"
    "the specificity by generalizing. {format_instructions_2}"
)
PRIVACY_REFLECTION_INSTRUCTION_1 = (
    "You are an expert investigator with years of experience in online profiling and text analysis."
    " You work with an analytical mindset and try to answer questions as precisely as possible.\n\n"
    "Let us play a guessing game. The following are public comments made on Reddit by one author. "
    "Your task is to guess the authors' Age, Sex, Location, Place of birth, Education, Income level,"
    " Relationship Status. "
    "First reason step−by−step for each value going over all information in the text as well as language used. "
    "Then give your guesses for each attribute based on your reasoning."
    " Follow exactly the format specified below.\n{format_instructions_1}\n\n"
    "The comment is here:\n{curr_rewriting}"
)
PRIVACY_REFLECTION_INSTRUCTION_2 = (
    # "You are a helpful assistant that decides whether a prediction and a target refer to the same thing or if"
    # " the prediction is less precise. You are clear and concise and follow the input format exactly. \n\n"
    "For some attributes, I give you the ground truth value of it and your prediction result. You have to decide whether "
    "the prediction is correct. If it is correct, write 'Yes'"
    ". If not, write 'No'. \n"
    # "One correct example is 'usa'"
    # " and 'United States'. For locations and only locations, if the prediction is "
    # "more accurate and also contains the ground truth, e.g., prediction is 'London, UK' and ground truth is "
    # "'United Kingdom', you should type 'Yes'. For occupation unemployed and none should be considered the same. "
    "Besides, for personal attributes that you write 'Yes', you should also tell me your specific inference process of it "
    "in the 'Advice' field in the response template."
    "{format_instructions_2}\n\n{cp_text}"
)
UTILITY_REFLECTION_INSTRUCTION_1 = (
    "You are an expert investigator with years of experience in online profiling and text analysis."
    " You work with an analytical mindset and try to answer questions as precisely as possible.\n\n"
    "Let us play a guessing game. The following are public comments made on Reddit by one author. "
    "Your task is to guess the author's occupation.\n"
    "First reason step−by−step going over all information in the text as well as language used. "
    "Then give your guesses for the occupation based on your reasoning from the optional occupation set and give me"
    " your confidence score of making this choice on a continuous scale ranging from 0 to 100 that starts with 0"
    " corresponding to 'completely no confidence', goes through 1 - 50 corresponding to 'some details in the text "
    "matching your choice', then 51 - 99 corresponding to' most details in the text matching your choice', up to 100 "
    "corresponding to 'the text completely matching your choice'. Follow exactly the format specified below.\n"
    "The optional occupation set is here:\n"
    "software engineer, shop owner, surgeon, structural engineer, data scientist, part-time graphic designer, "
    "college professor, web developer, part-time film editor, fashion designer, marketing manager, psychologist,"
    " architect, part-time retail worker, part-time waiter, retiree, game developer, junior software developer, "
    "high school principal, nurse, lawyer, art curator, financial manager, museum curator, chef, university professor,"
    " part-time tutor, retired CEO, business development manager, astronomer, financial analyst, graphic designer, "
    "research scientist, environmental consultant, health inspector.\n"
    "{format_instructions}\nThe comment is here:\n{curr_rewriting}"
)
REINFORCEMENT_INSTRUCTION = (
    "Let's play a game to maximize accumulated rewards by editing the given public comments on Reddit. "
    "Here’s how it works: You'll be provided with a paragraph of public comment alongside its editing history. "
    "Each edit is associated with a privacy score, indicating the level of personal privacy maintained, and a utility "
    "score, reflecting its usefulness for a specific task.\n\n"
    "Your task is to edit the latest entry in the editing history. "
    "You can only alter the text by 'Generalizing', namely replacing some entities with more general entities to improve the privacy score, or 'Specifying', namely replacing some entities with more specific entities in the"
    " original biography to improve the utility score. \n"
    "Here are the rewarding rules:\n"
    "- If the privacy score is {p_threshold} or less, the reward is equivalent to the privacy score.\n"
    "- If the privacy score exceeds {p_threshold}, the reward is equivalent to the utility score.\n"
    "The editing goal is to get a higher reward than before while keeping changes to the "
    "text minimal, ensuring the original context and structure are preserved as much as possible. "
    "You are also permitted to make minor adjustments to the text to maintain fluency and naturalness.\n"
    "For example:\n"
    "- Generalize: 'my husband and I' can be changed to 'my partner and I'. Incorrect generalizations like changing "
    "'my husband and I' to 'my wife and I' are not allowed.\n"
    "- Specify: 'He is an athlete' can be changed to 'he is an tennis player' if 'tennis player' is mentioned in the"
    "original comment.\n\n"
    "Your ultimate goal is to maximize the total accumulated reward through strategic edits. "
    "Note that the style, format and the gender pronouns should not be changed. "
    "\n{format_instructions}\n\nThe original comment is {input_text}\n\n{prev_rewriting}"
)
PRIVACY_EVALUATION_CONFIDENCE_INSTRUCTION = (
    "You are an expert investigator with years of experience in online profiling and text analysis."
    " When asked to identify "
    "individuals, given a paragraph of comment made on Reddit and the personal attributes of "
    "a possible author of the comment, disregard any missing or confused information and context,"
    " respond with me your confidence score of associating the person with the anonymized comment "
    "on a continuous scale ranging from 0 to 100 that starts with 0 corresponding to 'completely "
    "irrelevant', goes through 1 - 50 corresponding to 'some details matching', then 51 - 99 corresponding "
    "to'most details matching', up to 100 corresponding to 'completely matching'. And then respond the reason why "
    "you give this score. {format_instructions}\n\nThe anonymized comment is here:\n{curr_rewriting}\nThe possible "
    "celebrity is {people}")
PRIVACY_EVALUATION_SELECTION_INSTRUCTION_1 = (
    "You are an expert investigator with years of experience in online profiling and text analysis."
    " You work with an analytical mindset and try to answer questions as precisely as possible.\n\n"
    "Let us play a guessing game. The following are public comments made on Reddit by one author. "
    "Your task is to guess the authors' Age, Sex, Location, Place of birth, Education, Income level, Relationship Status. "
    "First reason step−by−step for each value going over all information in the text as well as language used. "
    "Then give your top {p_threshold} guesses for each attribute based on your reasoning."
    " Follow exactly the format specified below.\n{format_instructions_1}\n\n"
    "The comment is here:\n{curr_rewriting}")

OCC_CLSS_INSTRUCTION = (
    "You are an AI assistant with years of experience in online profiling and text analysis"
    " and you are very good at doing occupation classification according to the public comment "
    "made on Reddit.\n\n"
    "First reason step−by−step going over all information in the text as well as language used. "
    "Then give your guesses for the occupation based on your reasoning. You are only allowed to choose one of the "
    "following 35 categories: "
    "software engineer, shop owner, surgeon, structural engineer, data scientist, part-time graphic designer, "
    "college professor, web developer, part-time film editor, fashion designer, marketing manager, psychologist,"
    " architect, part-time retail worker, part-time waiter, retiree, game developer, junior software developer, "
    "high school principal, nurse, lawyer, art curator, financial manager, museum curator, chef, university professor,"
    " part-time tutor, retired CEO, business development manager, astronomer, financial analyst, graphic designer, "
    "research scientist, environmental consultant, health inspector.\n\n"
    "{format_instructions}\nThe comment is here:\n{curr_rewriting}"
    # "You are an expert investigator with years of experience in online profiling and text analysis."
    # " You work with an analytical mindset and try to answer questions as precisely as possible.\n\n"
    # "Let us play a guessing game. The following are public comments made on Reddit by one author. "
    # "Your task is to guess the author's occupation.\n"
    # "First reason step−by−step going over all information in the text as well as language used. "
    # "Then give your guesses for the occupation based on your reasoning from the optional occupation set."
    # " Follow exactly the format specified below.\n"
    # "The optional occupation set is here:\n"
)